### ISSUE TITLE
clippy action fails on PRs (specifically worse with dependabot)

### ISSUE THREAD

**Issue by 06kellyjac** [mbrubeck/agate#77]
https://github.com/actions-rs/clippy-check#limitations

And it's specifically worse with dependabot
https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807852653

solutions could be to remove it or ignore when PRs are from dependabot

another option is to check for write access before running the annotation action vs manual clippy

```
      - name: Check workflow permissions
        id: check_permissions
        uses: scherermichael-oss/action-has-permission@1.0.6
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy action to produce annotations
        uses: actions-rs/clippy-check@v1
        if: steps.check_permissions.outputs.has-permission
        with:
          args: --all-targets -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run clippy manually without annotations
        if: ${{ !steps.check_permissions.outputs.has-permission }}
        run: cargo clippy --all-targets -- -D warnings
```
